apiVersion: v1
kind: Service
metadata:
  name: ngix-svc
  namespace: default
spec:
  selector:
    run: ngix-pod
  type: LoadBalancer
  ports:
  - name: ngix-svc
    protocol: TCP
    port: 80
    targetPort: 80
