apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
# provisioner: kubernetes.io/
provisioner: example.com/nfs
parameters:
  path: /mnt/nfs_share
  server: 172.17.17.30
  size: 5Gi
reclaimPolicy: Retain
