apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-nfs-volume
  labels:
    type: local
spec:
  storageClassName: standard 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs_share
    server: 172.17.17.30
