apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  selector:
    app: mysql
  clusterIP: None
  ports:
  - name: myport
    protocol: TCP
    port: 3306
    targetPort: 3306
