apiVersion: v1
kind: Service
metadata:
  name: nodeapp-cluserip
  namespace: default
spec:
  selector:
    app: nodeapp 
  ports:
  - name: myport
    protocol: TCP
    port: 3000
    targetPort: 3000
