#kubectl label node kube-n2-cali type=dev
#kubectl label node kube-n1-cali tier=frontend

#kubectl label node kube-n1-cali tier-

apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:        
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: NotIn
            values:
            - frontend      
  containers:
  - name: with-node-affinity
    image: nginx