# kubectl label nodes kube-n1-cali tier=frontend
# kubectl label nodes kube-n1-cali type=dev

# kubectl label node <nodename> <labelname>-
# kubectl label node kube-n1-cali type-

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-nodeselector
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx
      nodeSelector:
        tier: frontend
        #type: main